import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import Providers from "./RTK/providers";

export const metadata = {
  title: "Sameh Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center justify-start h-screen">
        <div className="lg:w-[1600px] lg:max-w-[1600px] h-screen flex flex-col items-center mx-auto justify-start">
          <Navbar />
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
